apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{.Release.Name}}-cert
spec:
  secretName: {{.Release.Name}}-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{.Values.domain}}
