apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
spec:
  headers:
    sslProxyHeaders:
      X-Forwarded-Proto: "https"
    customRequestHeaders:
      Connection: "Upgrade"
      Upgrade: "websocket"
