apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-{{ .Release.Name }}
spec:
  redirectRegex:
    regex: {{.Values.domain}}(/?)$
    replacement: {{.Values.domain}}{{.Values.startRoomUrl}}
