apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "HostRegexp(`{host:virtual-office.+}`) && PathPrefix(`/api`)"
      priority: 1000
      services:
        - kind: Service
          name: {{ .Chart.Name }}-backend
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 80
  tls:
    secretName: {{.Release.Name}}-cert
    domains:
      - main: {{.Values.domain}}
