apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name" . }}-jvb
  labels: {{- include "jitsi-meet.labels" . | nindent 4 }}
spec:
  ports:
    - name: websocket
      port: 9090
      targetPort: websocket
    - name: tcp-stream
      port: 4443
      targetPort: tcp-stream
    - name: udp-stream
      port: 10000
      protocol: UDP
      targetPort: udp-stream
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name" . }}-jvb
    app.kubernetes.io/instance: {{ .Release.Name }}
