apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jitsi-meet.name" . }}-nginx-config-cm
  labels: {{- include "jitsi-meet.labels" . | nindent 4 }}
data:
  meet.conf: |-
    {{- .Files.Get "configs/web/nginx-meet.conf" | nindent 4 }}
