apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-{{ .Release.Name }}
spec:
  stripPrefix:
    prefixes:
      - "/play"
      - "/api"
      - "/maps"
      - "/pusher"
      - "/uploader"
