apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-uploader
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "HostRegexp(`{host:workadventure.+}`) && PathPrefix(`/uploader`)"
      priority: 1000
      middlewares:
        - name: strip-prefix-{{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
      services:
        - kind: Service
          name: {{ .Chart.Name }}-uploader
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 80
  tls:
    secretName: {{.Release.Name}}-cert
    domains:
      - main: {{.Values.domain}}
